### ISSUE TITLE
感谢dalao，三十周年真的要苟住！

### ISSUE THREAD

**Issue by icedrain0611** [daochouwangu/douyudanmu#3]
能不能增加弹幕随机滚动速度，降低字体粗细。现在看着有点粗了

**Comment by daochouwangu** [comment]
现在速度很快了，你可以自己调一下，这个参数比较个性化
 `dom.style.fontWeight = '800'` 这里的800变小就是字体变细（整百减小）
`dom.style.transition = 'transform 7s linear'` 这里的7s表示移动时间，变小会加快弹幕移动（如果要增加的话 setTimeout(function(){dom.remove()},7000) 里的7000也要增加，不然弹幕会提前消失）

**Comment by icedrain0611** [comment]
谢谢！
