### ISSUE TITLE
请问斗鱼视频的弹幕怎么搞

### ISSUE THREAD

**Issue by vigidroid** [daochouwangu/douyudanmu#4]
没想到6.1的插件10.1也能用上。
直播的弹幕是能看到了。
但是斗鱼视频（录播）的弹幕没有效果。
v.douyu.com

**Comment by daochouwangu** [comment]
插件原理是把评论区的弹幕显示到屏幕上，录播没有评论区，全都是服务器的数据，目前没有办法做到，可能要从斗鱼api取数据，太麻烦了。
